### ISSUE TITLE
Feature request: Purge database records and reseed

### ISSUE THREAD

**Issue by Firesphere** [isobar-nz/silverstripe-seeder#17]
Very useful for demo-sites, where random strangers can log onto. So the test-pages etc. are purged.

**Comment by chrisahhh** [comment]
Not sure if I understand the use case, do you mind elaborating with an example?

You can `framework/sake unseed` then `framework/sake seed` to refresh the seeded data

**Comment by Firesphere** [comment]
According to the docs, unseed only removes the seeded data. I'm talking about emptying the database completely and starting anew.

**Comment by chrisahhh** [comment]
Oh right I understand now. I think that its beyond the scope of this module, perhaps it would be more appropriate to create a silverstripe-demosite (can't think of a good name right now) module which uses the seeder to populate the initial data

**Comment by Firesphere** [comment]
Makes sense. But then again, why not include a "purge-and-seed" method? I think it fits with the aim of the module?

**Comment by chrisahhh** [comment]
When phrased that way I would tend to agree, I'll look into it!
